function getCitiesByState(stateName: string) {
  const citiesByState = {
    'Andhra Pradesh': [
      'Visakhapatnam',
      'Vijayawada',
      'Guntur',
      'Nellore',
      'Kurnool',
      'Rajahmundry',
      'Kakinada',
      'Tirupati',
      'Kadapa',
      'Anantapur',
    ],
    'Arunachal Pradesh': [
      'Itanagar',
      'Pasighat',
      'Naharlagun',
      'Roing',
      'Ziro',
      'Bomdila',
    ],
    Assam: [
      'Guwahati',
      'Silchar',
      'Dibrugarh',
      'Jorhat',
      'Nagaon',
      'Tinsukia',
      'Tezpur',
      'Sibsagar',
      'Barpeta',
      'Diphu',
    ],
    Bihar: [
      'Patna',
      'Gaya',
      'Bhagalpur',
      'Muzaffarpur',
      'Purnia',
      'Darbhanga',
      'Arrah',
      'Bihar Sharif',
      'Katihar',
      'Munger',
    ],
    Chhattisgarh: [
      'Raipur',
      'Bhilai',
      'Bilaspur',
      'Korba',
      'Durg',
      'Raigarh',
      'Rajnandgaon',
      'Jagdalpur',
      'Ambikapur',
      'Mahasamund',
    ],
    Goa: [
      'Panaji',
      'Margao',
      'Vasco da Gama',
      'Mapusa',
      'Ponda',
      'Bicholim',
      'Curchorem',
      'Cuncolim',
      'Quepem',
      'Sanguem',
    ],
    Gujarat: [
      'Ahmedabad',
      'Surat',
      'Vadodara',
      'Rajkot',
      'Bhavnagar',
      'Jamnagar',
      'Junagadh',
      'Gandhinagar',
      'Nadiad',
      'Morbi',
    ],
    Haryana: [
      'Faridabad',
      'Gurugram (Gurgaon)',
      'Panipat',
      'Ambala',
      'Yamunanagar',
      'Rohtak',
      'Hisar',
      'Karnal',
      'Sonipat',
      'Panchkula',
    ],
    'Himachal Pradesh': [
      'Shimla',
      'Mandi',
      'Solan',
      'Nahan',
      'Una',
      'Palampur',
      'Hamirpur',
      'Bilaspur',
      'Chamba',
      'Kangra',
    ],
    'Jammu and Kashmir': [
      'Srinagar',
      'Jammu',
      'Anantnag',
      'Baramulla',
      'Kathua',
      'Sopore',
      'Pulwama',
      'Kupwara',
      'Udhampur',
      'Rajouri',
    ],
    Jharkhand: [
      'Ranchi',
      'Jamshedpur',
      'Dhanbad',
      'Bokaro',
      'Deoghar',
      'Hazaribagh',
      'Giridih',
      'Ramgarh',
      'Medininagar',
    ],
    Karnataka: [
      'Bengaluru (Bangalore)',
      'Mysore',
      'Hubli-Dharwad',
      'Mangalore',
      'Belgaum',
      'Gulbarga',
      'Davanagere',
      'Bellary',
      'Bijapur',
      'Shimoga',
    ],
    Kerala: [
      'Thiruvananthapuram',
      'Kochi (Cochin)',
      'Kozhikode (Calicut)',
      'Thrissur',
      'Kollam',
      'Palakkad',
      'Alappuzha',
      'Kannur',
      'Kottayam',
      'Manjeri',
    ],
    'Madhya Pradesh': [
      'Indore',
      'Bhopal',
      'Jabalpur',
      'Gwalior',
      'Ujjain',
      'Sagar',
      'Dewas',
      'Satna',
      'Ratlam',
      'Rewa',
    ],
    Maharashtra: [
      'Mumbai',
      'Pune',
      'Nagpur',
      'Nashik',
      'Thane',
      'Aurangabad',
      'Solapur',
      'Kalyan-Dombivali',
      'Vasai-Virar',
      'Amravati',
    ],
    Manipur: [
      'Imphal',
      'Thoubal',
      'Kakching',
      'Bishnupur',
      'Churachandpur',
      'Senapati',
      'Ukhrul',
      'Tamenglong',
      'Jiribam',
      'Kangpokpi',
    ],
    Meghalaya: [
      'Shillong',
      'Tura',
      'Nongstoin',
      'Jowai',
      'Williamnagar',
      'Baghmara',
      'Resubelpara',
      'Mawkyrwat',
      'Mairang',
      'Khliehriat',
    ],
    Mizoram: [
      'Aizawl',
      'Lunglei',
      'Saiha',
      'Champhai',
      'Serchhip',
      'Lawngtlai',
      'Mamit',
      'Kolasib',
      'Hnahthial',
      'Khawzawl',
    ],
    Nagaland: [
      'Kohima',
      'Dimapur',
      'Mokokchung',
      'Tuensang',
      'Zunheboto',
      'Wokha',
      'Phek',
      'Mon',
      'Kiphire',
      'Longleng',
    ],
    'Odisha (Orissa)': [
      'Bhubaneswar',
      'Cuttack',
      'Rourkela',
      'Brahmapur',
      'Sambalpur',
      'Puri',
      'Balasore',
      'Bhadrak',
      'Baripada',
      'Jharsuguda',
    ],
    Punjab: [
      'Ludhiana',
      'Amritsar',
      'Jalandhar',
      'Patiala',
      'Bathinda',
      'Pathankot',
      'Hoshiarpur',
      'Mohali',
      'Batala',
      'Moga',
    ],
    Rajasthan: [
      'Jaipur',
      'Jodhpur',
      'Kota',
      'Bikaner',
      'Ajmer',
      'Udaipur',
      'Bhilwara',
      'Alwar',
      'Sikar',
      'Pali',
    ],
    Sikkim: [
      'Gangtok',
      'Namchi',
      'Gyalshing',
      'Mangan',
      'Ravangla',
      'Singtam',
      'Soreng',
      'Sikandra',
      'Jorethang',
      'Rangpo',
    ],
    'Tamil Nadu': [
      'Chennai',
      'Coimbatore',
      'Madurai',
      'Tiruchirappalli',
      'Tiruppur',
      'Salem',
      'Erode',
      'Vellore',
      'Thoothukkudi (Tuticorin)',
      'Dindigul',
    ],
    Telangana: [
      'Hyderabad',
      'Warangal',
      'Nizamabad',
      'Khammam',
      'Karimnagar',
      'Ramagundam',
      'Mahbubnagar',
      'Adilabad',
      'Nalgonda',
      'Suryapet',
    ],
    Tripura: [
      'Agartala',
      'Udaipur',
      'Dharmanagar',
      'Kailasahar',
      'Belonia',
      'Khowai',
      'Amarpur',
      'Kamalpur',
      'Ambassa',
      'Sabroom',
    ],
    'Uttar Pradesh': [
      'Lucknow',
      'Kanpur',
      'Ghaziabad',
      'Agra',
      'Meerut',
      'Varanasi',
      'Allahabad',
      'Moradabad',
      'Aligarh',
      'Saharanpur',
    ],
    Uttarakhand: [
      'Dehradun',
      'Haridwar',
      'Roorkee',
      'Haldwani-cum-Kathgodam',
      'Bageshwar',
      'Rudrapur',
      'Kashipur',
      'Ranikhet',
      'Pithoragarh',
      'Manglaur',
    ],
    'West Bengal': [
      'Kolkata (Calcutta)',
      'Asansol',
      'Siliguri',
      'Durgapur',
      'Bardhaman',
      'Malda',
      'Baharampur',
      'Habra',
      'Kharagpur',
      'Shantipur',
    ],
  };
  return citiesByState[stateName] || [];
}

export {getCitiesByState};
